#!/usr/bin/env bash
# Printss "To infinity and beyond" indefinitely with
# Sleep 2 in between each iteration.
# Prints "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
