#!/usr/bin/env bash
# Printing "Best School" 10 times using a while loop.
# In the 9th time print hi

x=0

while [ $x -lt 10 ]
do
  if [ $x -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( x++ ))
done
