#!/usr/bin/env bash
# Prints the time for 12 horus and 59 minutes.
#   Displays hour from 0 to 12
#   Displays minute from 1 to 59

x=0

while [ $x -le 12 ]
do
  echo "Hour: $x"
  y=1
  while [ $y -le 59 ]
  do
    echo "$y"
    (( y++ ))
  done
  (( x++ ))
done

