#!/usr/bin/env bash
# Prints the contents of the current directory in list format.
#   Displays the part of the name after the first dash. 

list=$(ls)
for x in $list; do
  echo "$x" | cut -d '-' -f2
done
